### PR TITLE
Fixed vuex-shared-mutations peer dependency

### PR DESCRIPTION
**Pull request by qkdreyer**
vuex-shared-mutations@0.0.3" has incorrect peer dependency "vuex@^2.0.0"

### CODE REVIEW

**Comment by qkdreyer** [comment]
👍

**Comment by qkdreyer** [comment]
Could you release a v0.0.4 ?

**Comment by qkdreyer** [comment]
Bump @xanf

**Comment by xanf** [comment]
Sorry, will do today @qkdreyer

**Comment by qkdreyer** [comment]
Bump @xanf

**Comment by xanf** [comment]
@qkdreyer Sorry once again, ETA ~12h,  travelling now :)

**Comment by qkdreyer** [comment]
Bump @xanf

**Comment by qkdreyer** [comment]
Bump @xanf

**Comment by qkdreyer** [comment]
Bump @xanf

**Comment by qkdreyer** [comment]
Bump @xanf 😢

**Comment by xanf** [comment]
Sorry, @qkdreyer 
Just done it

**Comment by qkdreyer** [comment]
Thanks 🙏

**Pull request merged**
